### ISSUE TITLE
Issues with the Atlas screen example

### ISSUE THREAD

**Issue by barkby** [dual-universe/lua-examples#22] opened 2022-10-16 06:18 UTC
Hi
Not sure if it is me or an update but for some reason when I paste the **render.lua** code into the screen I get a script error:

attempt to index a number value(local 'v').
![image](https://user-images.githubusercontent.com/9532453/196021163-c442ebbe-441b-4a9b-9b26-44e24175a1ac.png)

**Comment by aCandidMind** [comment] 2022-12-04 02:58
Same here

**Comment by Jericho1060** [comment] 2023-01-06 11:30
@barkby @aCandidMind 
it should be solved now, there is still an error when clicking Thades for now due to the script tying to load too many images, i'll update it soon again

**Comment by Jericho1060** [comment] 2023-01-06 14:51
Solved, issue can be closed

**Comment by NQ-Ligo** [comment] 2023-01-06 15:01
The issue is fixed, a big thank you to @Jericho1060 ! I close the issue

**Closed by NQ-Ligo** 2023-01-06 15:01 UTC
